version: '3.8'

services:
  app:
    build:
      context: ./purchases
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./purchases:/var/www
    depends_on:
      - db
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./purchases:/var/www
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:13
    container_name: laravel-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  vue-app:
    build:
      context: ./purchases-frontend
      dockerfile: Dockerfile
    image: vue-app
    container_name: vue-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./purchases-frontend:/app
    ports:
      - "8080:8080"
    networks:
      - laravel

networks:
  laravel:

volumes:
  pgdata:
